@startuml
actor Aluno
actor Professor
actor SistemaDeCobrança

usecase "Matricular-se em disciplinas" as UC1
usecase "Cancelar matrículas" as UC2
usecase "Consultar matrícula" as UC3
usecase "Consultar alunos matriculados" as UC4
usecase "Receber notificação de matrícula" as UC5

Aluno -- UC1
Aluno -- UC2
Aluno -- UC3
Professor -- UC4
SistemaDeCobrança -- UC5

UC1 .> UC5 : <<include>>
UC2 .> UC5 : <<include>>
@enduml
